import HackathonInformation from "../interfaces/HackathonInformation";
export const HackathonList: HackathonInformation[] = [
  {
    name: "SB Hacks 2021",
    place: "UC Santa Barbara",
    city: "Santa Barbara",
    state: "CA",
    organizer: "SB Hacks",
    type: "Online",
    role: "Participant",
    awards: [],
    date: new Date("2021-01-15T00:00:00.000Z"),
    latitude: 34.4129,
    longitude: -119.8489,
    github: ["https://github.com/to-mmy/you-tify/"],
    projectName: "You-tify",
    devpost: "https://devpost.com/software/you-tify",
  },
  {
    name: "SacHacks 2021",
    place: "Sacramento State University",
    city: "Sacramento",
    state: "CA",
    organizer: "SacHacks",
    type: "Online",
    role: "Participant",
    awards: [],
    date: new Date("2021-02-19T00:00:00.000Z"),
    latitude: 38.5613,
    longitude: -121.4241,
    github: ["https://github.com/dylanvu/sketchedout"],
    projectName: "SketchedOut",
    devpost: "https://devpost.com/software/sketchedout",
  },
  {
    name: "LA Hacks 2021",
    place: "UCLA",
    city: "Los Angeles",
    state: "CA",
    organizer: "LA Hacks",
    type: "Online",
    role: "Participant",
    awards: ["1st Place Overall", "Best Level Up Hack"],
    date: new Date("2021-03-21T00:00:00.000Z"),
    latitude: 34.0689,
    longitude: -118.4452,
    github: ["https://github.com/dlo03/lahacks-vr"],
    projectName: "G.R.I.P. - Grasp Responsive Inflatable Pouch Controller",
    devpost:
      "https://devpost.com/software/grip-controller-grasp-responsive-inflatable-pouch-controller",
  },
  {
    name: "Pinnacle 2021",
    place: "Dallas/Fort Worth Airport Marriott",
    city: "Dallas",
    state: "TX",
    organizer: "Pinnacle",
    type: "In-Person",
    role: "Participant",
    awards: [],
    date: new Date("2021-09-17T00:00:00.000Z"),
    latitude: 32.8494,
    longitude: -97.0404,
    github: ["https://github.com/dylanvu/pinnacle"],
    projectName: "G.R.I.P. Board",
    devpost: "https://devpost.com/software/g-r-i-p-board",
  },
  {
    name: "HackHarvard 2021",
    place: "Harvard University",
    city: "Cambridge",
    state: "MA",
    organizer: "Hack Harvard",
    type: "Online",
    role: "Participant",
    awards: ["Most Creative Use of Twilio"],
    date: new Date("2021-10-08T00:00:00.000Z"),
    latitude: 42.3736,
    longitude: -71.1097,
    github: [
      "https://github.com/dylanvu/fsyncbackend",
      "https://github.com/simaha63/F.Sync",
    ],
    projectName: "F•Sync",
    devpost: "https://devpost.com/software/f-sync",
  },
  {
    name: "CalHacks 2021",
    place: "UC Berkeley",
    city: "Berkeley",
    state: "CA",
    organizer: "CalHacks",
    type: "Online",
    role: "Participant",
    awards: [],
    date: new Date("2021-10-22T00:00:00.000Z"),
    latitude: 37.8715,
    longitude: -122.273,
    github: [
      "https://gitlab.com/m4667/flutter_frontend",
      "https://gitlab.com/m4667/backend",
    ],
    projectName: "Geoverse",
    devpost: "https://devpost.com/software/geoverse",
  },
  {
    name: "SB Hacks 2022",
    place: "UC Santa Barbara",
    city: "Santa Barbara",
    state: "CA",
    organizer: "SB Hacks",
    type: "Online",
    role: "Participant",
    awards: ["Best Space App"],
    date: new Date("2022-02-04T00:00:00.000Z"),
    latitude: 34.4129,
    longitude: -119.8489,
    github: [
      "https://github.com/kdeng23/Wordship-Game",
      "https://github.com/moomoo02/BackEndWordShip",
      "https://github.com/moomoo02/FrontEndWordShip",
    ],
    projectName: "WordShip",
    devpost: "https://devpost.com/software/wordship",
  },
  {
    name: "ZotHacks 2022",
    place: "UC Irvine",
    city: "Irvine",
    state: "CA",
    organizer: "HackAtUCI",
    type: "In-Person",
    role: "Mentor",
    awards: ["1st Place"],
    date: new Date("2022-11-05T00:00:00.000Z"),
    latitude: 33.6405,
    longitude: -117.8443,
  },
  {
    name: "UCI WebJam 2022",
    place: "UC Irvine",
    city: "Irvine",
    state: "CA",
    organizer: "UCI ICS Student Council",
    type: "In-Person",
    role: "Participant",
    awards: ["2nd Place"],
    date: new Date("2022-11-14T00:00:00.000Z"),
    latitude: 33.6405,
    longitude: -117.8443,
    github: ["https://github.com/tyleryy/Rattle"],
    projectName: "Rattle",
  },
  {
    name: "IrvineHacks 2023",
    place: "UC Irvine",
    city: "Irvine",
    state: "CA",
    organizer: "HackAtUCI",
    type: "In-Person",
    role: "Participant",
    awards: [],
    date: new Date("2023-02-03T00:00:00.000Z"),
    latitude: 33.6405,
    longitude: -117.8443,
    github: [
      "https://github.com/dylanvu/Caption-Firmware",
      "https://github.com/dylanvu/Caption-Frontend",
      "https://github.com/dylanvu/Caption-Node-Test",
      "https://github.com/typhocannon/Caption-Software",
    ],
    projectName: "Caption",
    devpost: "https://devpost.com/software/caption",
  },
  {
    name: "LA Hacks 2023",
    place: "UCLA",
    city: "Los Angeles",
    state: "CA",
    organizer: "LA Hacks",
    type: "In-Person",
    role: "Participant",
    awards: [],
    date: new Date("2023-04-21T00:00:00.000Z"),
    latitude: 34.0689,
    longitude: -118.4452,
    github: [
      "https://github.com/dylanvu/LA-Hacks-2023",
      "https://github.com/typhocannon/la_hacks",
    ],
    projectName: "BlockStalk",
    devpost: "https://devpost.com/software/blockstalk",
  },
  {
    name: "ZotHacks 2023",
    place: "UC Irvine",
    city: "Irvine",
    state: "CA",
    organizer: "HackAtUCI",
    type: "In-Person",
    role: "Mentor",
    awards: ["2nd Place"],
    date: new Date("2023-11-03T00:00:00.000Z"),
    latitude: 33.6405,
    longitude: -117.8443,
  },
  {
    name: "UCI WebJam 2023",
    place: "UC Irvine",
    city: "Irvine",
    state: "CA",
    organizer: "UCI ICS Student Council",
    type: "In-Person",
    role: "Participant",
    awards: ["3rd Place"],
    date: new Date("2023-11-13T00:00:00.000Z"), // Nov 13, 2023
    latitude: 33.6405,
    longitude: -117.8443,
    github: [
      "https://github.com/sharonm6/fishgpt-frontend",
      "https://github.com/dylanvu/FishGPT-CV",
      "https://github.com/dylanvu/FishGPT-Backend",
    ],
    projectName: "FishGPT",
  },
  {
    name: "React Jam Winter 2023",
    place: "San Francisco",
    city: "San Francisco",
    state: "CA",
    organizer: "Rune",
    type: "Online",
    role: "Participant",
    awards: ["Honorable Mention"],
    date: new Date("2023-12-26T00:00:00.000Z"), // Dec 26, 2023
    latitude: 37.7749,
    longitude: -122.4194,
    github: ["https://github.com/dylanvu/SweetStack"],
    projectName: "SweetStack",
  },
  {
    name: "SB Hacks X 2024",
    place: "UC Santa Barbara",
    city: "Santa Barbara",
    state: "CA",
    organizer: "SB Hacks",
    type: "In-Person",
    role: "Participant",
    awards: [],
    date: new Date("2024-01-12T00:00:00.000Z"), // Jan 12, 2024
    latitude: 34.4129,
    longitude: -119.8489,
    github: [
      "https://github.com/dylanvu/SB-Hacks-X-Backend",
      "https://github.com/bphan4bryant/XpireFrontEnd",
    ],
    projectName: "Xpire",
    devpost: "https://devpost.com/software/xpire-gh31qp",
  },
  {
    name: "RoseHacks 2024",
    place: "UC Riverside",
    city: "Riverside",
    state: "CA",
    organizer: "RoseHack",
    type: "In-Person",
    role: "Participant",
    awards: ["Best UI/UX"],
    date: new Date("2024-01-20T00:00:00.000Z"), // Jan 20, 2024
    latitude: 33.9736,
    longitude: -117.3276,
    github: ["https://github.com/KevinWu098/mammo"],
    projectName: "Mammo",
    devpost: "https://devpost.com/software/mammo",
  },
  {
    name: "IrvineHacks 2024",
    place: "UC Irvine",
    city: "Irvine",
    state: "CA",
    organizer: "HackAtUCI",
    type: "In-Person",
    role: "Participant",
    awards: ["Hacker's Choice"],
    date: new Date("2024-01-26T00:00:00.000Z"), // Jan 26, 2024
    latitude: 33.6405,
    longitude: -117.8443,
    github: ["https://github.com/dylanvu/Amelia-Software"],
    projectName: "Amelia",
    devpost: "https://devpost.com/software/amelia",
  },
  {
    name: "QWER Hacks 2024",
    place: "UCLA",
    city: "Los Angeles",
    state: "CA",
    organizer: "QWER Hacks",
    type: "In-Person",
    role: "Participant",
    awards: ["Most Creative"],
    date: new Date("2024-02-02T00:00:00.000Z"), // Feb 2, 2024
    latitude: 34.0689,
    longitude: -118.4452,
    github: [
      "https://github.com/bphan4bryant/QwerHacksFrontEnd",
      "https://github.com/dylanvu/Trigger-Finger-Tango-Backend",
    ],
    projectName: "Trigger Finger Tango",
    devpost: "https://devpost.com/software/finger-guns",
  },
  {
    name: "FullyHacks 2024",
    place: "CSU Fullerton",
    city: "Fullerton",
    state: "CA",
    organizer: "FullyHacks",
    type: "In-Person",
    role: "Participant",
    awards: ["Most Technical"],
    date: new Date("2024-02-24T00:00:00.000Z"), // Feb 24, 2024
    latitude: 33.8824,
    longitude: -117.8815,
    github: ["https://github.com/IdkwhatImD0ing/CyberTank"],
    projectName: "CyberTank",
  },
  {
    name: "Hack Merced 2024",
    place: "UC Merced",
    city: "Merced",
    state: "CA",
    organizer: "Hack Merced",
    type: "In-Person",
    role: "Participant",
    awards: ["Spatial & Interactivity Track: 2nd Place"],
    date: new Date("2024-03-08T00:00:00.000Z"), // Mar 8, 2024
    latitude: 37.364,
    longitude: -120.434,
    github: ["https://github.com/dylanvu/PyPointer"],
    projectName: "PyPointer",
    devpost: "https://devpost.com/software/pypointer",
  },
  {
    name: "Uncommon Hacks 2024",
    place: "University of Chicago",
    city: "Chicago",
    state: "IL",
    organizer: "Uncommon Hacks",
    type: "In-Person",
    role: "Participant",
    awards: ["Best in Track: Programmatic Art"],
    date: new Date("2024-03-23T00:00:00.000Z"), // Mar 23, 2024
    latitude: 41.831,
    longitude: -87.607,
    github: ["https://github.com/dylanvu/Mad-Lyrics"],
    projectName: "Mad Lyrics",
    devpost: "https://devpost.com/software/mad-lyrics",
  },
  {
    name: "YHack 2024",
    place: "Yale University",
    city: "New Haven",
    state: "CT",
    organizer: "YHack",
    type: "In-Person",
    role: "Participant",
    awards: ["Best Overall"],
    date: new Date("2024-03-30T00:00:00.000Z"), // Mar 30, 2024
    latitude: 41.3111,
    longitude: -72.9267,
    github: ["https://github.com/dylanvu/Tidbits"],
    projectName: "Tidbits",
    devpost: "https://devpost.com/software/tidbits-n9mrxa",
  },
  {
    name: "DiamondHacks 2024",
    place: "UCSD",
    city: "San Diego",
    state: "CA",
    organizer: "UCSD ACM",
    type: "In-Person",
    role: "Participant",
    awards: ["Best in Track: Captain's Classroom (Education)"],
    date: new Date("2024-04-06T00:00:00.000Z"), // Apr 6, 2024
    latitude: 32.8801,
    longitude: -117.234,
    github: ["https://github.com/IdkwhatImD0ing/ABSeas"],
    projectName: "ABSeas",
    devpost: "https://devpost.com/software/abseas",
  },
  {
    name: "Google AI x MHacks",
    place: "University of Michigan",
    city: "Ann Arbor",
    state: "MI",
    organizer: "MHacks",
    type: "In-Person",
    role: "Participant",
    awards: [],
    date: new Date("2024-04-03T00:00:00.000Z"), // Apr 3, 2024
    latitude: 42.2923,
    longitude: -83.7155,
    github: ["https://github.com/KevinWu098/gemUI"],
    projectName: "GemUI",
    devpost: "https://devpost.com/software/gemui",
  },
  {
    name: "LA Hacks 2024",
    place: "UCLA",
    city: "Los Angeles",
    state: "CA",
    organizer: "LA Hacks",
    type: "In-Person",
    role: "Participant",
    awards: [],
    date: new Date("2024-04-20T00:00:00.000Z"), // Apr 20, 2024
    latitude: 34.0689,
    longitude: -118.4452,
    github: [
      "https://github.com/typhocannon/lahack2024frontend",
      "https://github.com/dylanvu/LA-Hacks-2024-Backend-Firmware",
    ],
    projectName: "Haptic Definition",
    devpost: "https://devpost.com/software/haptic-definition",
  },
  {
    name: "Davis Hacks 2024",
    place: "UC Davis",
    city: "Davis",
    state: "CA",
    organizer: "Davis Hacks",
    type: "In-Person",
    role: "Participant",
    awards: ["2nd/3rd Place Intel Developer Cloud"],
    date: new Date("2024-04-27T00:00:00.000Z"), // Apr 27, 2024
    latitude: 38.5449,
    longitude: -121.7405,
    github: ["https://github.com/IdkwhatImD0ing/DoggoAI"],
    projectName: "Doggo AI",
    devpost: "https://devpost.com/software/doggo-ai",
  },
  {
    name: "VenusHacks 2024",
    place: "UC Irvine",
    city: "Irvine",
    state: "CA",
    organizer: "VenusHacks",
    type: "In-Person",
    role: "Participant",
    awards: [],
    date: new Date("2024-05-24T00:00:00.000Z"), // May 24, 2024
    latitude: 33.6405,
    longitude: -117.8443,
    github: ["https://github.com/dylanvu/Sechism-Sniper"],
    projectName: "Sechism Sniper",
    devpost: "https://devpost.com/software/discrimination-destroyer",
  },
  {
    name: "STEMist Hacks III",
    place: "Maker Nexus",
    city: "Sunnyvale",
    state: "CA",
    organizer: "STEMist Education",
    type: "Online",
    role: "Participant",
    awards: [],
    date: new Date("2024-07-19T00:00:00.000Z"), // Jul 19, 2024
    latitude: 37.4122,
    longitude: -122.0062,
    github: ["https://github.com/dylanvu/Deduction-Buddy"],
    projectName: "Deduction Buddy",
    devpost: "https://devpost.com/software/deduction-buddy",
  },
  {
    name: "The Future of Data 2024",
    place: "University of Cincinnati",
    city: "Cincinnati",
    state: "OH",
    organizer: "University of Cincinnati",
    type: "Online",
    role: "Participant",
    awards: ["Social Impact Best Software"],
    date: new Date("2024-08-26T00:00:00.000Z"),
    latitude: 39.1325,
    longitude: -84.5152,
    github: ["https://github.com/StephanieNhiLe/drowsy-guard"],
    projectName: "DrowsyGuard",
    devpost: "https://devpost.com/software/drowsyguard",
  },
  {
    name: "Cerebral Beach Hacks 2024",
    place: "1217 Second Street",
    city: "Santa Monica",
    state: "CA",
    organizer: "AI LA",
    type: "In-Person",
    role: "Participant",
    awards: ["Best Cybersecurity Hack (Third Place)"],
    date: new Date("2024-10-12T00:00:00.000Z"),
    latitude: 34.0173,
    longitude: -118.4993,
    github: ["https://github.com/dylanvu/Marlin"],
    projectName: "Marlin",
    devpost: "https://devpost.com/software/marlin",
  },
  {
    name: "CalHacks 2024",
    place: "The Metreon",
    city: "San Francisco",
    state: "CA",
    organizer: "CalHacks",
    type: "In-Person",
    role: "Mentor",
    awards: [],
    date: new Date("2024-10-18T00:00:00.000Z"),
    latitude: 37.7833,
    longitude: -122.4036,
  },
  {
    name: "SoCal Tech Week 2024",
    place: "USC",
    city: "Los Angeles",
    state: "CA",
    organizer: "SCHacks",
    type: "In-Person",
    role: "Mentor",
    awards: [],
    date: new Date("2024-11-09T00:00:00.000Z"),
    latitude: 34.0224,
    longitude: -118.2851,
  },
  {
    name: "HackCC 2024",
    place: "Orange Coast College",
    city: "Costa Mesa",
    state: "CA",
    organizer: "HackCC",
    type: "In-Person",
    role: "Mentor",
    awards: [],
    date: new Date("2024-11-09T00:00:00.000Z"),
    latitude: 33.6658,
    longitude: -117.9114,
  },
  {
    name: "UCI WebJam 2024",
    place: "UC Irvine",
    city: "Irvine",
    state: "CA",
    organizer: "UCI ICS Student Council",
    type: "Online",
    role: "Mentor",
    awards: [],
    date: new Date("2024-11-18T00:00:00.000Z"),
    latitude: 33.6405,
    longitude: -117.8443,
  },
  {
    name: "Audrey Chen jia.seed Brainrot Hackathon",
    place: "Michigan State University",
    city: "East Lansing",
    state: "MI",
    organizer: "Audrey Chen",
    type: "Online",
    role: "Mentor",
    awards: [],
    date: new Date("2024-11-26T00:00:00.000Z"),
    latitude: 42.7011,
    longitude: -84.4817,
  },
  {
    name: "SB Hacks 2025",
    place: "UC Santa Barbara",
    city: "Santa Barbara",
    state: "CA",
    organizer: "SB Hacks",
    type: "Online",
    role: "Mentor",
    awards: [],
    date: new Date("2025-01-11T00:00:00.000Z"),
    latitude: 34.4129,
    longitude: -119.8489,
  },
  {
    name: "Nosu AI Hackathon",
    place: "San Francisco",
    city: "San Francisco",
    state: "CA",
    organizer: "Nosu",
    type: "Online",
    role: "Mentor",
    awards: [],
    date: new Date("2025-01-11T00:00:00.000Z"),
    latitude: 37.7749,
    longitude: -122.4194,
  },
  {
    name: "Irvine Hacks 2025",
    place: "UC Irvine",
    city: "Irvine",
    state: "CA",
    organizer: "HackAtUCI",
    type: "In-Person",
    role: "Mentor",
    awards: [],
    date: new Date("2025-01-24T00:00:00.000Z"),
    latitude: 33.6405,
    longitude: -117.8443,
  },
  {
    name: "hack night",
    place: "Ziba Photo Video",
    city: "Irvine",
    state: "CA",
    organizer: "tech night",
    type: "In-Person",
    role: "Mentor",
    awards: [],
    date: new Date("2025-02-22T00:00:00.000Z"),
    latitude: 33.6882,
    longitude: -117.8585,
  },
  {
    name: "Athena Hacks 2025",
    place: "USC",
    city: "Los Angeles",
    state: "CA",
    organizer: "Athena Hacks",
    type: "In-Person",
    role: "Mentor",
    awards: [],
    date: new Date("2025-03-01T00:00:00.000Z"),
    latitude: 34.0224,
    longitude: -118.2851,
  },
  {
    name: "Beach Hacks 2025",
    place: "CSU Long Beach",
    city: "Long Beach",
    state: "CA",
    organizer: "Beach Hacks",
    type: "In-Person",
    role: "Mentor",
    awards: [],
    date: new Date("2025-03-22T00:00:00.000Z"),
    latitude: 33.7835,
    longitude: -118.1142,
  },
  {
    name: "BitHacks 2025",
    place: "UC Irvine",
    city: "Irvine",
    state: "CA",
    organizer: "UCI IEEE",
    type: "In-Person",
    role: "Mentor",
    awards: [],
    date: new Date("2025-04-11T00:00:00.000Z"),
    latitude: 33.6405,
    longitude: -117.8443,
  },
  {
    name: "LA Hacks 2025",
    place: "UCLA",
    city: "Los Angeles",
    state: "CA",
    organizer: "LA Hacks",
    type: "In-Person",
    role: "Mentor",
    awards: [],
    date: new Date("2025-04-25T00:00:00.000Z"),
    latitude: 34.0689,
    longitude: -118.4452,
  },
];
