// import Navbar from '@/components/Navbar'
import ParticlesBg from '@/components/ParticlesBg'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// fix the large flashing icon: https://blog.cetindere.de/fix-huge-flashing-icons-fontawesome/
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from "@fortawesome/fontawesome-svg-core";
// Prevent fontawesome from dynamically adding its css since we are going to include it manually
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main">
          {/* floating particles in background  */}
          <ParticlesBg />
          {children}
        </div>
      </body>
    </html>
  )
}

// export function PageLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <div>
//       <Navbar />
//       <div className="content-container">
//         <div className="content">
//           {children}
//         </div>
//       </div>
//     </div >
//   )
// }